import type { Metadata } from "next";
import { Tajawal} from "next/font/google";
import "./globals.css";
import ProviderReactQuery from "@/providers/providerReactQuery";
import { Toaster } from 'react-hot-toast';



const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${tajawal.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProviderReactQuery>
          <Toaster 
           toastOptions={{
            duration: 3000,
            position: "top-left",
           }}
          />
          {children}
        </ProviderReactQuery>
      </body>
    </html>
  );
}
